name: 'Delete'

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      days: 
        description: 'Number of days.'
        required: true
        default: 1
      runs: 
        description: 'Number of runs.'
        required: true
        default: 1

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.runs }}
