name: share
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '0 2,3,4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1 
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
          npm install request
          npm install md5-node
      - name: '运行1'
        run: | 
          node youth1share.js
      - name: '运行2'
        run: | 
          node youth2share.js
